version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: focusboost-postgres
    environment:
      POSTGRES_DB: focusboost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - focusboost-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: focusboost-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - focusboost-network

  # FocusBoost API Server
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: focusboost-api
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: focusboost
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      CLIENT_URL: http://localhost:5173
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - focusboost-network

  # FocusBoost Frontend (Development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: focusboost-frontend
    environment:
      VITE_API_URL: http://localhost:3001/api
      VITE_WS_URL: http://localhost:3001
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - focusboost-network

volumes:
  postgres_data:
  redis_data:

networks:
  focusboost-network:
    driver: bridge